### ISSUE TITLE
Double serialization

### ISSUE THREAD

**Issue by jeremeamia** [liuggio/spawn#3]
I was looking at your `ClosureProcessFactory`, and I think you may be double serializing. Doing `$this->fnSerializer->serialize($closure)` on [L50](https://github.com/liuggio/concurrent/blob/f1cc46b67ee6076d59d74910d82b10befbd2af78/src/Process/ClosureProcessFactory.php#L50) should return the serialized string, as defined in the [`Serializer`'s interface](https://github.com/jeremeamia/super_closure/blob/master/src/SerializerInterface.php#L16), and you should not need to call `serialize()` again on [L55](https://github.com/liuggio/concurrent/blob/f1cc46b67ee6076d59d74910d82b10befbd2af78/src/Process/ClosureProcessFactory.php#L55). Likewise, you will want to adjust your unserialization logic to only unserialize once.

**Comment by liuggio** [comment]
thanks @jeremeamia
