### ISSUE TITLE
Adding 3rd party services

### ISSUE THREAD

**Issue by liuggio** [liuggio/spawn#5]
@EmanueleMinotto  ask me to add:
- [x] travis
- [ ] styleci
- [ ] insight.sensiolabs.com
- [ ] coveralls.io

**Comment by liuggio** [comment]
I added travis with https://github.com/liuggio/spawn/commit/c28b0119facc1829e487a3ce84c40f39175f459b 
for the other I don't see big benefit except the insight ...

**Comment by EmanueleMinotto** [comment]
Just nice to have, anyway travis is enough :)

**Comment by EmanueleMinotto** [comment]
@liuggio this issue can be closed if other services aren't interesting
